### ISSUE TITLE
Symbol's function definition is void: tool-bar-mode

### ISSUE THREAD

**Issue by xyproto** [susam/emacs4cl#1]
Hi, I get this error message when trying out the `.emacs` file on Emacs 27.1 on Arch Linux:

```
Warning (initialization): An error occurred while loading ‘/home/user/.emacs’:

Symbol's function definition is void: tool-bar-mode

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

**Comment by susam** [comment]
Thank you for reporting this issue. I could reproduce the issue on Debian GNU/Linux 10.6 (buster). I have now fixed the issue in commit dcb5c6440ab894b2f2567f5029ca35860fc08ebd.
